@startuml
left to right direction
actor "Cliente" as C
actor "Vendedor" as V
actor "Gerente do Departamento" as G
actor "Fornecedor" as F

rectangle Sistema {
  
  (Cadastrar Cliente) as UC1
  (Manter Endereço do Cliente) as UC2
  (Criar Pedido de Compra) as UC3
  (Gerenciar Itens do Pedido) as UC4
  (Consultar Pedido de Compra) as UC5

  (Cadastrar Vendedor) as UC6
  (Cadastrar Departamento) as UC7
  (Cadastrar Produto) as UC8
  (Cadastrar Fornecedor) as UC9
}

' Casos de uso do Vendedor
V --> UC1
V --> UC2
V --> UC3
V --> UC4
V --> UC5

' Casos de uso do Gerente
G --> UC6
G --> UC7
G --> UC8
G --> UC9

' Interação Cliente <-> Vendedor
C --> V
F --> G

@enduml
