"plantuml.exportOutDir": "docs/diagrams/out"

@startuml
left to right direction
actor "Vendedor" as V
actor "Gerente do Departamento" as G

rectangle Sistema {
  
  (Cadastrar Cliente) as UC1
  (Manter Endereço do Cliente) as UC2
  (Criar Pedido de Compra) as UC3
  (Gerenciar Itens do Pedido) as UC4
  (Consultar Pedido de Compra) as UC5

  (Cadastrar Vendedor) as UC6
  (Cadastrar Departamento) as UC7
  (Cadastrar Produto) as UC8
  (Cadastrar Fornecedor) as UC9
}

V --> UC1
V --> UC2
V --> UC3
V --> UC4
V --> UC5

G --> UC6
G --> UC7
G --> UC8
G --> UC9
@enduml
